/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufpe.cin.five.gui.project;

import br.ufpe.cin.five.core.data.DriverType;

/**
 *
 * @author vocallab
 */
public class DataBaseSelectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataBaseSelectionPanel
     */
    public DataBaseSelectionPanel() {
        initComponents();
    }

    public DriverType getDriverType()
    {
        if(chkDriver.getSelectedIndex() == 0) return DriverType.Mysql;
        else if(chkDriver.getSelectedIndex() == 1) return DriverType.Postgres;
        else  return null;

    }
    
    public boolean validateDataBase()
    {
        boolean validation = false;
        if(chkDriver.getSelectedIndex() == 2) validation = true;
        
        if(chkDriver.getSelectedIndex() == 0 ||chkDriver.getSelectedIndex() == 1){
            if(!txtUrlDB.getText().isEmpty() &&
               !txtLoginDB.getText().isEmpty()
              )
            validation = true;
        }
        
        return validation;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chkDriver = new javax.swing.JComboBox();
        panelDBData = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUrlDB = new javax.swing.JTextField();
        txtLoginDB = new javax.swing.JTextField();
        txtPasswordDB = new javax.swing.JPasswordField();

        jLabel1.setText("Especifique a banco de dados a ser utilizado.");

        jLabel2.setText("Driver: ");

        chkDriver.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mysql" }));
        chkDriver.setName("chkDriver");
        chkDriver.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DriveritemStateChanged(evt);
            }
        });

        panelDBData.setName("panelDataBaseData");

        jLabel3.setText("Url:");

        jLabel4.setText("Login:");

        jLabel5.setText("Senha:");

        txtUrlDB.setText("localhost:3306");
        txtUrlDB.setName("txtUrlBD");

        txtLoginDB.setText("root");
        txtLoginDB.setName("txtLoginBD");

        javax.swing.GroupLayout panelDBDataLayout = new javax.swing.GroupLayout(panelDBData);
        panelDBData.setLayout(panelDBDataLayout);
        panelDBDataLayout.setHorizontalGroup(
            panelDBDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDBDataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelDBDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelDBDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUrlDB, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoginDB, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordDB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panelDBDataLayout.setVerticalGroup(
            panelDBDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDBDataLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelDBDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUrlDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDBDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLoginDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDBDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPasswordDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelDBData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chkDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelDBData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DriveritemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DriveritemStateChanged
        // TODO add your handling code here:
        
        if(chkDriver.getSelectedIndex() == 0)// MySQL
        {
            panelDBData.setVisible(true);
        }else if(chkDriver.getSelectedIndex() == 1) // Postgres
        {
            panelDBData.setVisible(true);
        }else if(chkDriver.getSelectedIndex() == 2) // Derby
        {
            panelDBData.setVisible(false);
        }
    }//GEN-LAST:event_DriveritemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox chkDriver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelDBData;
    public javax.swing.JTextField txtLoginDB;
    public javax.swing.JPasswordField txtPasswordDB;
    public javax.swing.JTextField txtUrlDB;
    // End of variables declaration//GEN-END:variables
}
