/**
 * Copyright 2011 Federal University of Pernambuco.
 * All Rights Reserved.  Use is subject to license terms.
 *
 * This file is part of FIVE (Framework for an Integrated Voice Environment).
 *
 */
package br.ufpe.cin.five.gui.project;

import br.ufpe.cin.five.core.data.DriverType;
import br.ufpe.cin.five.core.data.DriverUtils;
import br.ufpe.cin.five.core.project.Project;
import br.ufpe.cin.five.exception.RegisterException;
import br.ufpe.cin.five.facade.Facade;
import java.awt.Color;
import java.io.File;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author Alexandre
 */
public class NewProjetctDialog extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(NewProjetctDialog.class);
    
    private Facade facade = Facade.getInstance();
    
    private ProjectTypePanel ptp;
    private NameProjectPanel pnl;   
    private DataBaseSelectionPanel pdb;
    private boolean pressedButton = true;

    /** Creates new form TelaProjetos */
    public NewProjetctDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        logger.info("Inicializando componentes de GUI.");

        initComponents();

        setLocationRelativeTo(null);
        setSize(587, 321);
        jPanel2.setSize(126, 222);

        ptp = new ProjectTypePanel();
        pnl = new NameProjectPanel();
        pdb = new DataBaseSelectionPanel();

        jTabbedPane1.add(ptp, 0);
        jTabbedPane1.setTitleAt(0, "Tipo do Projeto");

        jTabbedPane1.add(pnl, 1);
        jTabbedPane1.setTitleAt(1, "Nome e Local");
        
        jTabbedPane1.add(pdb,2);
        jTabbedPane1.setTitleAt(2, "Banco de Dados");
                
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btAvancar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btOk = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo projeto");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(890, 49));

        btAvancar.setText("Avançar >");
        btAvancar.setName("btProximo"); // NOI18N
        btAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvancarActionPerformed(evt);
            }
        });

        btVoltar.setText("< Voltar");
        btVoltar.setEnabled(false);
        btVoltar.setName("btVoltar"); // NOI18N
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btOk.setText("OK");
        btOk.setEnabled(false);
        btOk.setMaximumSize(new java.awt.Dimension(75, 23));
        btOk.setMinimumSize(new java.awt.Dimension(75, 23));
        btOk.setName("btFinalizar"); // NOI18N
        btOk.setPreferredSize(new java.awt.Dimension(75, 23));
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.setName("btCancelar"); // NOI18N
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAvancar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAvancar)
                    .addComponent(btVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);
        jPanel2.setMaximumSize(new java.awt.Dimension(126, 222));
        jPanel2.setMinimumSize(new java.awt.Dimension(126, 222));

        jLabel3.setForeground(java.awt.Color.blue);
        jLabel3.setText("1. Tipo do Projeto");

        jLabel4.setText("2. Nome e Local");

        jLabel1.setText("3. Escolha do Banco de Dados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Passos:");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        logger.info("Botao cancel pressionado.");
        facade.setProject(null);
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void avancar() {
        logger.info("Botao avancar pressionado.");
        pressedButton = true;
        if(jLabel3.getForeground().equals(Color.blue))
        {
            if (Facade.getInstance().getProject() != null) {
                jLabel3.setForeground(Color.black);
                jLabel4.setForeground(Color.blue);
                btVoltar.setEnabled(true);                                
                jTabbedPane1.setSelectedIndex(1);
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um projeto.");
                jTabbedPane1.setSelectedIndex(0);
            }
        }else if(jLabel4.getForeground().equals(Color.blue))
        {
            if(pnl.tfProjectName.getText().isEmpty() || pnl.tfProjectPath.getText().isEmpty())
            {
            JOptionPane.showMessageDialog(null, "Selecione um nome e local para o projeto.");
                jTabbedPane1.setSelectedIndex(1);
            }else
            {
                jLabel3.setForeground(Color.black);
                jLabel4.setForeground(Color.black);
                jLabel1.setForeground(Color.blue);
                btAvancar.setEnabled(false);
                btVoltar.setEnabled(true);
                btOk.setEnabled(true);
                jTabbedPane1.setSelectedIndex(2);
            }
        }
    }

    private void voltar() {
        logger.info("Botao voltar pressionado.");
        pressedButton = true;
        if(jLabel4.getForeground().equals(Color.blue))
        {
            jLabel3.setForeground(Color.blue);
            jLabel4.setForeground(Color.black);
            btVoltar.setEnabled(false);
            btAvancar.setEnabled(true);
            btOk.setEnabled(false);
            jTabbedPane1.setSelectedIndex(0);
        }else if (jLabel1.getForeground().equals(Color.blue))
        {
            jLabel1.setForeground(Color.black);
            jLabel4.setForeground(Color.blue);
            btVoltar.setEnabled(true);
            btAvancar.setEnabled(true);
            btOk.setEnabled(false);
            jTabbedPane1.setSelectedIndex(1);
        }
        
    }

    private void btAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvancarActionPerformed
        avancar();
    }//GEN-LAST:event_btAvancarActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        voltar();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        try {
            logger.info("Botão OK pressionado");

            if (validateProjectAttributes()) {

                Project project = facade.getProject();
                if (project != null){
                    project.setName(pnl.getProjectName());
                    project.setDirectory(pnl.getPath() + File.separator + pnl.getProjectName());
                    project.setDbLogin(pdb.txtLoginDB.getText());
                    project.setDbPassword(new String(pdb.txtPasswordDB.getPassword()));
                    project.setDbDriver(pdb.getDriverType());
                    project.setDbUrl(DriverUtils.getConnectionURL(pdb.txtUrlDB.getText(),project.getDbDriver())+"/"+project.getName());                    
                    facade.setProject(project);
                    logger.info("Pasta do projeto selecionada foi "+pnl.getPath());
                }

                facade.createProject(facade.getProject());
                facade.initProjectRegisters();

                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível criar o projeto. Verifique se todas as informações necessárias foram fornecidas.");
                logger.warn("Não foi possível criar o projeto. Verifique se todas as informações necessárias foram fornecidas.");
            }

        } catch (RegisterException ex) {
            logger.error("", ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } 
    }//GEN-LAST:event_btOkActionPerformed

    private boolean validateProjectAttributes() {
        boolean validation = true;
        if (facade.getProject() == null) {
            validation = false;                        
        }
        validation = pdb.validateDataBase();        
        return validation;
    }

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if(!pressedButton)
        {
            if (jTabbedPane1.getSelectedIndex() == 0) {
                voltar();
            } else {
                avancar();
            }
        }else
        {
            pressedButton = false;
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAvancar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btOk;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
