/**
 * Copyright 2011 Federal University of Pernambuco.
 * All Rights Reserved.  Use is subject to license terms.
 *
 * This file is part of FIVE (Framework for an Integrated Voice Environment).
 *
 */
package br.ufpe.cin.five.gui.classification;

import br.ufpe.cin.five.gui.dialogs.ResultsDialog;
import br.ufpe.cin.five.core.classification.Classification;
import br.ufpe.cin.five.exception.RegisterException;
import br.ufpe.cin.five.facade.Facade;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.log4j.Logger;

/**
 *
 * @author Alexandre
 */
public class ClassificationPanel extends javax.swing.JPanel {
     
    private static final Logger logger = Logger.getLogger(ClassificationPanel.class);
    
    Facade facade = Facade.getInstance();    
    
    private int selectedLine;
    
    private TableRowSorter<TableModel> sorter;
    private DefaultTableModel model;

    /** Creates new form ClassificationPanel */
    public ClassificationPanel() {
        logger.info("Inicializando ClassificationPanel.");
        initComponents();
//        sorter = new TableRowSorter<TableModel>(model);
//        jTable1.setRowSorter(sorter);
    }

    public int getSelectedLine() {
        return selectedLine;
    }

    public void setSelectedLine(int selectedLine) {
        this.selectedLine = selectedLine;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btProcess = new javax.swing.JButton();
        btInsert = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        tfTechnique = new javax.swing.JTextField();
        jlTechnique = new javax.swing.JLabel();
        tfDescription = new javax.swing.JTextField();
        jlDescription = new javax.swing.JLabel();
        btSearch = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(676, 473));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Técnica", "Descrição", "Classificado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btProcess.setText("Classificar");
        btProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProcessActionPerformed(evt);
            }
        });

        btInsert.setText("Incluir");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        btUpdate.setText("Alterar");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btRemove.setText("Excluir");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btProcess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                .addComponent(btInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRemove)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btProcess)
                    .addComponent(btRemove)
                    .addComponent(btUpdate)
                    .addComponent(btInsert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlTechnique.setText("id:");

        jlDescription.setText("Descrição:");

        btSearch.setText("Pesquisar");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTechnique)
                    .addComponent(tfTechnique, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(tfDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSearch))
                    .addComponent(jlDescription))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTechnique)
                    .addComponent(jlDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTechnique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch)
                    .addComponent(tfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProcessActionPerformed
        logger.info("O botão btProcess foi pressionado.");
        int line = jTable1.getSelectedRow();
        if (line >= 0) {
            Classification classification = (Classification) jTable1.getValueAt(line, 2);            
            ResultsDialog dialog = new ResultsDialog(null, true, classification);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        }
        addAllLinesTableClassification();
}//GEN-LAST:event_btProcessActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if(evt.getClickCount() == 2) {
            btUpdateActionPerformed(null);
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        logger.info("Botão btSearch pressionado.");
        String text = "";
        if (!tfTechnique.getText().equals("") && !tfDescription.getText().equals("")) {
            JOptionPane.showMessageDialog(jPanel4, "Escolha apenas um dos campos para pesquisar", "Pesquisar Classificação", selectedLine);
        } else {
            if (!tfTechnique.getText().equals("")) {
                text = tfTechnique.getText();
            }
            if (!tfDescription.getText().equals("")) {
                text = tfDescription.getText();
            }
            if (text.length() == 0) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter(text));
            }
        }
    }//GEN-LAST:event_btSearchActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        logger.info("O botão btRemove foi pressionado.");
        if (JOptionPane.showConfirmDialog(null, "Deseja excluir a classificação?", "Excluir classificação", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            logger.info("Usuário confirmou a exclusao.");
            int line = jTable1.getSelectedRow();
            if (line >= 0) {
                try {
                    int id = Integer.parseInt(jTable1.getValueAt(line, 0).toString());
                    Classification classification = facade.searchClassification(id);
                    
                    facade.removeClassification(classification);
                    removeLine(line, jTable1);
                    
                    logger.info("Classificação excluída com sucesso.");
                    JOptionPane.showMessageDialog(null, "Classificação excluída com sucesso!");
                } catch (final RegisterException ex) {
                    logger.error(ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
}//GEN-LAST:event_btRemoveActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        logger.info("O botão btUpdate foi pressionado.");
        int line = jTable1.getSelectedRow();        
        if (line >= 0) {
            try {
                int id = Integer.parseInt(jTable1.getValueAt(line, 0).toString());
                Classification classification = facade.searchClassification(id);
                ClassificationDialog dialog = new ClassificationDialog(null, true, classification, 1);
                dialog.pack();
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);
                removeLine(line, jTable1);
                addAllLinesTableClassification();
            } catch (final RegisterException ex) {
                logger.error(ex.getMessage());
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }            
        }
}//GEN-LAST:event_btUpdateActionPerformed

    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed
        logger.info("O botão btInsert foi pressionado.");
        ClassificationDialog dialog = new ClassificationDialog(null, true, null, 0);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        addAllLinesTableClassification();
}//GEN-LAST:event_btInsertActionPerformed

    protected void addLineTableClassification(Classification classification) {
        model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{classification.getId(), classification.getTechnique().toString(), classification, classification.isActive()});
    }

    public void addAllLinesTableClassification() {
        removeAllLinesTableClassification();
        for (Classification classification : facade.getProject().getClassifications()) {
            addLineTableClassification(classification);
        }
    }

    protected void updateLineTableClassification(String sentence, int line) {
        model = (DefaultTableModel) jTable1.getModel();
        model.setValueAt(sentence, line, 0);
    }

    private void removeAllLinesTableClassification() {
        model = (DefaultTableModel) jTable1.getModel();
        while (model.getRowCount() >= 1) {
            model.removeRow(0);
        }
    }

    private void removeLine(int line, JTable table) {
        model = (DefaultTableModel) table.getModel();
        model.removeRow(line);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btProcess;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btUpdate;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlDescription;
    private javax.swing.JLabel jlTechnique;
    private javax.swing.JTextField tfDescription;
    private javax.swing.JTextField tfTechnique;
    // End of variables declaration//GEN-END:variables

}
