
package br.ufpe.cin.five.gui.classification;

import br.ufpe.cin.five.core.classification.hmm.HmmStatesType;
import br.ufpe.cin.five.core.classification.hmm.HmmTopology;
import br.ufpe.cin.five.core.classification.hmm.HmmUnitSize;
import javax.swing.DefaultComboBoxModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Alexandre
 */
public class PanelHMMParams extends javax.swing.JPanel {

    private static final Logger logger = Logger.getLogger(PanelHMMParams.class);

    /** Creates new form PainelSVM */
    public PanelHMMParams() {        
        logger.info("Inicializando PanelHMMParams.");
        initComponents();

        cbStatesType.setModel(new DefaultComboBoxModel(HmmStatesType.values()));
        cbTopology.setModel(new DefaultComboBoxModel(HmmTopology.values()));
        cbUnitSize.setModel(new DefaultComboBoxModel(HmmUnitSize.values()));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNumGaussians = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNumIteractions = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfNumHERests = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbStatesType = new javax.swing.JComboBox();
        tfNumStates = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbTopology = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbUnitSize = new javax.swing.JComboBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Número de Gaussianas:");

        tfNumGaussians.setText("10");

        jLabel3.setText("Número de Iterações:");

        tfNumIteractions.setText("10");

        jLabel4.setText("Número de HERest:");

        tfNumHERests.setText("3");

        jLabel2.setText("Número de Estado:");

        tfNumStates.setText("1");
        tfNumStates.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel5.setText("Topologia do HMM:");

        cbTopology.setMinimumSize(new java.awt.Dimension(77, 18));

        jLabel6.setText("Topologia do HMM:");

        cbUnitSize.setMinimumSize(new java.awt.Dimension(77, 18));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumGaussians, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumHERests, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumIteractions, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbTopology, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbStatesType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbUnitSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNumStates, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumGaussians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfNumIteractions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cbTopology, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfNumStates, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbStatesType, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNumHERests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbUnitSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbStatesType;
    private javax.swing.JComboBox cbTopology;
    private javax.swing.JComboBox cbUnitSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfNumGaussians;
    private javax.swing.JTextField tfNumHERests;
    private javax.swing.JTextField tfNumIteractions;
    private javax.swing.JTextField tfNumStates;
    // End of variables declaration//GEN-END:variables

    public int getNumGaussianas() {
        return new Integer(tfNumGaussians.getText());
    }

    public void setNumGaussianas(int numGaussianas) {
        tfNumGaussians.setText(numGaussianas + "");
    }

    public int getNumIteractions() {
        return tfNumIteractions.getText().equals("") ? 0 : Integer.parseInt(tfNumIteractions.getText());
    }

    public void setNumIteractions(int iterations) {
        tfNumIteractions.setText(iterations + "");
    }

    public int getNumHERests() {
        return tfNumHERests.getText().equals("") ? 0 : Integer.parseInt(tfNumHERests.getText());
    }

    public void setNumHERests(int numIteracoes) {
        tfNumHERests.setText(numIteracoes + "");
    }

    public int getNumStates() {
        return tfNumStates.getText().equals("") ? 0 : Integer.parseInt(tfNumStates.getText());
    }

    public void setNumStates(int numGaussianas) {
        tfNumStates.setText(numGaussianas + "");
    }

    public HmmStatesType getType() {
        return (HmmStatesType) cbStatesType.getSelectedItem();
    }

    public void setType(HmmStatesType type) {
        cbStatesType.setSelectedItem(type);
    }
    
    public HmmTopology getTopology() {
        return (HmmTopology) cbTopology.getSelectedItem();
    }

    public void setTopology(HmmTopology topology) {
        cbTopology.setSelectedItem(topology);
    }
    
    public HmmUnitSize getUnitSize() {
        return (HmmUnitSize) cbUnitSize.getSelectedItem();
    }

    public void setUnitSize(HmmUnitSize unitSize) {
        cbUnitSize.setSelectedItem(unitSize);
    }    
}
