/**
 * Copyright 2011 Federal University of Pernambuco.
 * All Rights Reserved.  Use is subject to license terms.
 *
 * This file is part of FIVE (Framework for an Integrated Voice Environment).
 *
 */
package br.ufpe.cin.five.gui.dictionary;

import br.ufpe.cin.five.exception.RegisterException;
import br.ufpe.cin.five.facade.Facade;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author Alexandre
 */
public class DictionaryDialog extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(DictionaryDialog.class);
    private Facade facade = Facade.getInstance();
    private int operation;
    String oldPhoneticRepresentation;

    /** Creates new form WordDialog */
    public DictionaryDialog(java.awt.Frame parent, boolean modal, String word, String phoneticRepresentation, int operation) {
        super(parent, modal);

        logger.info("Inicializando Word Dialog. Operation = " + operation);
        initComponents();
        this.operation = operation;
        if (operation == 1) {
            oldPhoneticRepresentation = phoneticRepresentation;
            tfWord.setText(word);
            tfWord.setEnabled(false);
            tfPhoneticRepresentation.setText(phoneticRepresentation);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlPhoneticRepresentation = new javax.swing.JLabel();
        tfPhoneticRepresentation = new javax.swing.JTextField();
        jlWord = new javax.swing.JLabel();
        tfWord = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dicionário");

        jlPhoneticRepresentation.setText("Representação Fonética:");

        jlWord.setText("Palavra:");

        btSave.setText("Salvar");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPhoneticRepresentation)
                    .addComponent(tfPhoneticRepresentation, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jlWord)
                    .addComponent(tfWord, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlPhoneticRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPhoneticRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        logger.info("O botao btSave foi pressionado. Operation = " + operation);
        if (validateFields()) {
            logger.info("Campos validados.");
            try {
                if (operation == 0) {
                    facade.insertPhoneticRepresentation(tfWord.getText(), tfPhoneticRepresentation.getText());
                    logger.info("Representação Fonética incluída com sucesso.");
                    JOptionPane.showMessageDialog(null, "Representação Fonética incluída com sucesso");
                } else if (operation == 1) {
                    facade.updatePhoneticRepresentation(tfWord.getText(), oldPhoneticRepresentation, tfPhoneticRepresentation.getText());
                    logger.info("Representação Fonética alterada com sucesso.");
                    JOptionPane.showMessageDialog(null, "Representação Fonética alterada com sucesso");
                }
            } catch (RegisterException ex) {
                logger.error(ex);
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            this.setVisible(false);
        } else {
            logger.warn("Informe os parâmetros necessários");
            JOptionPane.showMessageDialog(null, "Informe os parâmetros necessários");
        }  
    }//GEN-LAST:event_btSaveActionPerformed

    private boolean validateFields() {
        if (tfWord.getText().equals("")
                || tfPhoneticRepresentation.getText().equals("")) {                
            return false;
        } else {
            return true;
        }
    }        
        
    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel jlPhoneticRepresentation;
    private javax.swing.JLabel jlWord;
    private javax.swing.JTextField tfPhoneticRepresentation;
    private javax.swing.JTextField tfWord;
    // End of variables declaration//GEN-END:variables
}
