/**
 * Copyright 2011 Federal University of Pernambuco.
 * All Rights Reserved.  Use is subject to license terms.
 *
 * This file is part of FIVE (Framework for an Integrated Voice Environment).
 *
 */
package br.ufpe.cin.five.gui.dictionary;

import br.ufpe.cin.five.core.utterance.Phrase;
import br.ufpe.cin.five.core.utterance.Utterance;
import br.ufpe.cin.five.core.utterance.Word;
import br.ufpe.cin.five.exception.RegisterException;
import br.ufpe.cin.five.facade.Facade;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.log4j.Logger;

/**
 *
 * @author Alexandre
 */
public class DictionaryPanel extends javax.swing.JPanel {

    private static final Logger logger = Logger.getLogger(DictionaryPanel.class);
    
    Facade facade = Facade.getInstance();
    
    private int selectedLine;
    
    private DefaultTableModel model;
    private TableRowSorter<TableModel> sorter;

    /** Creates new form TelaLocutor */
    public DictionaryPanel() {
        logger.info("Inicializando Word Panel.");
        initComponents();
//        sorter = new TableRowSorter<TableModel>(model);
//        jTable1.setRowSorter(sorter);
    }

    public int getSelectedLine() {
        return selectedLine;
    }

    public void setSelectedLine(int selectedLine) {
        this.selectedLine = selectedLine;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btInsert = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btHistogram = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        tfWord = new javax.swing.JTextField();
        jlWord = new javax.swing.JLabel();
        tfPhoneticRepresentation = new javax.swing.JTextField();
        jlPhoneticRepresentation = new javax.swing.JLabel();
        btSearch = new javax.swing.JButton();

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Palavra", "Representação Fonética"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btInsert.setText("Incluir");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        btUpdate.setText("Alterar");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        btRemove.setText("Excluir");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        btHistogram.setText("Histograma");
        btHistogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistogramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btHistogram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRemove)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btRemove)
                    .addComponent(btUpdate)
                    .addComponent(btInsert)
                    .addComponent(btHistogram))
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlWord.setText("Palavra:");

        jlPhoneticRepresentation.setText("Representação Fonética:");

        btSearch.setText("Pesquisar");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlWord)
                    .addComponent(tfWord, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(tfPhoneticRepresentation, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSearch))
                    .addComponent(jlPhoneticRepresentation))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlWord)
                    .addComponent(jlPhoneticRepresentation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch)
                    .addComponent(tfPhoneticRepresentation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if (evt.getClickCount() == 2) {
            btUpdateActionPerformed(null);
        }
}//GEN-LAST:event_jTable1MousePressed

    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed
        logger.info("Botão btInsert pressionado.");
        DictionaryDialog dialog = new DictionaryDialog(null, true, null, null, 0);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        addAllLinesTableWord();
}//GEN-LAST:event_btInsertActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        logger.info("O botão btUpdate foi pressionado.");
        int line = jTable1.getSelectedRow();
        if (line >= 0) {
            String word = (String) jTable1.getValueAt(line, 0);
            String phoneticRepresentation = (String) jTable1.getValueAt(line, 1);
            logger.info("Abrindo Word Dialog para alteracao do registro.");
            DictionaryDialog dialog = new DictionaryDialog(null, true, word, phoneticRepresentation, 1);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
            removeLine(line, jTable1);
            addAllLinesTableWord();
        }
}//GEN-LAST:event_btUpdateActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        logger.info("O botão btRemove foi pressionado.");
        if (JOptionPane.showConfirmDialog(null, "Deseja excluir a representação fonética?", "Excluir representação fonética", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            logger.info("O usuario confirmou a exclusão.");
            int line = jTable1.getSelectedRow();
            if (line >= 0) {
                try {
                    String wordDescription = (String) jTable1.getValueAt(line, 0);
                    String phoneticRepresentation = (String) jTable1.getValueAt(line, 1);
                    Facade.getInstance().removePhoneticRepresentation(wordDescription, phoneticRepresentation);
                    removeLine(line, jTable1);
                    logger.info("Representacao fonética excluída com sucesso!");
                    JOptionPane.showMessageDialog(null, "Representação fonética excluída com sucesso!", "Excluir representação fonétic", JOptionPane.INFORMATION_MESSAGE);
                } catch (RegisterException ex) {
                    logger.error(ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
}//GEN-LAST:event_btRemoveActionPerformed

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        logger.info("Botão btSearch pressionado.");
        String text = "";
        if (!tfWord.getText().equals("") && !tfPhoneticRepresentation.getText().equals("")) {
            JOptionPane.showMessageDialog(jPanel5, "Escolha apenas um dos campos para pesquisar", "Pesquisar Representação Fonética", selectedLine);
        } else {
            if (!tfWord.getText().equals("")) {
                text = tfWord.getText();
            }
            if (!tfPhoneticRepresentation.getText().equals("")) {
                text = tfPhoneticRepresentation.getText();
            }
            if (text.length() == 0) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter(text));
            }
        }
}//GEN-LAST:event_btSearchActionPerformed

    private void btHistogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistogramActionPerformed
        logger.info("Botão btHistogram pressionado.");
        try {
            facade.generateHistogram();
            logger.info("Histograma gerado em: " + Facade.getInstance().getProject().getDirectory() + "/histograma.txt");
            JOptionPane.showMessageDialog(this, "Histograma gerado em: " + Facade.getInstance().getProject().getDirectory() + "/histograma.txt");
        } catch (RegisterException ex) {
            logger.error(ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btHistogramActionPerformed

    protected void addLineTableWord(String word, String phoneticRepresentation) {
        model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new String[]{word, phoneticRepresentation});
    }

    public void addAllLinesTableWord() {
        removeAllLinesTableWord();
        List<String> reps = new ArrayList<String>();
        List<Utterance> utterances = Facade.getInstance().getProject().getUtterances();
        for (Utterance utterance : utterances) {
            List<Phrase> phrases = utterance.getPhrases();
            for (Phrase phrase : phrases) {
                List<Word> words = phrase.getWords();
                for (Word word : words) {
                    List<String> representations = word.getPhoneticRepresentations();
                    for (String representation : representations) {
                        if (!reps.contains(representation.trim())) {
                            reps.add(representation);
                            addLineTableWord(word.getDescription(), representation);
                        }
                    }
                }
            }
        }
    }

    protected void updateLineTableWord(String sentence, int line) {
        model = (DefaultTableModel) jTable1.getModel();
        model.setValueAt(sentence, line, 0);
    }

    private void removeAllLinesTableWord() {
        model = (DefaultTableModel) jTable1.getModel();
        while (model.getRowCount() >= 1) {
            model.removeRow(0);
        }
    }

    private void removeLine(int line, JTable table) {
        model = (DefaultTableModel) table.getModel();
        model.removeRow(line);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHistogram;
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btRemove;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btUpdate;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlPhoneticRepresentation;
    private javax.swing.JLabel jlWord;
    private javax.swing.JTextField tfPhoneticRepresentation;
    private javax.swing.JTextField tfWord;
    // End of variables declaration//GEN-END:variables
}
