/**
 * Copyright 2011 Federal University of Pernambuco.
 * All Rights Reserved.  Use is subject to license terms.
 *
 * This file is part of FIVE (Framework for an Integrated Voice Environment).
 *
 */
package br.ufpe.cin.five.gui.utterance;

import br.ufpe.cin.five.core.utterance.Utterance;
import br.ufpe.cin.five.exception.RegisterException;
import br.ufpe.cin.five.facade.Facade;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author Alexandre
 */
public class UtteranceDialog extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(UtteranceDialog.class);
    private Facade facade = Facade.getInstance();
    private int operation;
    private Utterance utterance;

    /** Creates new form UtteranceDialog */
    public UtteranceDialog(java.awt.Frame parent, boolean modal, Utterance utterance, int operation) {
        super(parent, modal);

        logger.info("Inicializando Utterance Dialog. Operation = " + operation);
        initComponents();
                
        this.operation = operation;
        this.utterance = utterance;
        
        if (operation == 1) {            
            this.utterance = utterance;            
            taUtterance.setText(utterance.getDescription());
        } else {
            this.utterance = new Utterance();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlUtterance = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taUtterance = new javax.swing.JTextArea();
        btSave = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Locução");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlUtterance.setText("Digite a Locução:");

        taUtterance.setColumns(20);
        taUtterance.setLineWrap(true);
        taUtterance.setRows(5);
        taUtterance.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taUtterance);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                    .addComponent(jlUtterance))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlUtterance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        btSave.setText("Salvar");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        logger.info("Botão btSave pressionado. Operation = " + operation);
        if (validateFields()) {
            logger.info("Campos validados.");
            try {
                utterance.setDescription(taUtterance.getText());            
                if(operation == 0) {            
                    facade.insertUtterance(utterance);            
                    logger.info("Locução inserida com sucesso.");
                    JOptionPane.showMessageDialog(null, "Locução inserida com sucesso.");
                } else {
                    facade.updateUtterance(utterance);            
                    logger.info("Locução alterada com sucesso.");
                    JOptionPane.showMessageDialog(null, "Locução alterada com sucesso.");
                }            
                this.setVisible(false);        
            } catch (RegisterException ex) {            
                logger.error(ex.getMessage());
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            logger.warn("Informe os parâmetros necessários");
            JOptionPane.showMessageDialog(null, "Informe os parâmetros necessários");
        }             
    }//GEN-LAST:event_btSaveActionPerformed

    private boolean validateFields() {
        if (taUtterance.getText().equals("")) {                
            return false;
        } else {
            return true;
        }
    }    
    
    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        logger.info("Botão btCancel pressionado.");
        this.setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlUtterance;
    private javax.swing.JTextArea taUtterance;
    // End of variables declaration//GEN-END:variables
}
