
package br.ufpe.cin.five.gui.extraction;

import org.apache.log4j.Logger;

/**
 *
 * @author Alexandre
 */
public class PanelMGCCParams extends javax.swing.JPanel {

    private static final Logger logger = Logger.getLogger(PanelMGCCParams.class);

    /** Creates new form PanelLPCProperties */
    public PanelMGCCParams() {
        logger.info("Inicializando PanelMGCCProperties");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txFatorDistorcaoFrequencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txPesoPoleZeroAnaliseMGC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txDesvioPadraoParaRuidosBrancos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txTamanhoFFT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txOrdemAnaliseMGC = new javax.swing.JTextField();
        txLimiteInferiorExtracaoF0 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txLimiteSuperiorExtracaoF0 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbNormalizacao = new javax.swing.JComboBox();
        cbJanelamento = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbGanho = new javax.swing.JComboBox();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(760, 150));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Fator de Distorção:");

        txFatorDistorcaoFrequencia.setText("0.42");

        jLabel12.setText("Peso polo/zero:");

        txPesoPoleZeroAnaliseMGC.setText("0");

        jLabel16.setText("DP para ruídos brancos:");

        txDesvioPadraoParaRuidosBrancos.setText("50");

        jLabel9.setText("Tamanho do FFT (pt):");

        txTamanhoFFT.setText("512");

        jLabel13.setText("Ordem da Análise MGC:");

        txOrdemAnaliseMGC.setText("24");

        txLimiteInferiorExtracaoF0.setText("60");

        jLabel15.setText("-");

        txLimiteSuperiorExtracaoF0.setText("400");

        jLabel11.setText("Limites para F0:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTamanhoFFT, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txFatorDistorcaoFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txDesvioPadraoParaRuidosBrancos))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txOrdemAnaliseMGC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(10, 10, 10)
                        .addComponent(txPesoPoleZeroAnaliseMGC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txLimiteInferiorExtracaoF0, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txLimiteSuperiorExtracaoF0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txTamanhoFFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txFatorDistorcaoFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txDesvioPadraoParaRuidosBrancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txOrdemAnaliseMGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txPesoPoleZeroAnaliseMGC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txLimiteInferiorExtracaoF0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txLimiteSuperiorExtracaoF0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(11, 11, 11))
        );

        jLabel8.setText("Normalização:");

        cbNormalizacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEM NORMALIZAÇÃO", "POTÊNCIA", "MAGNITUDE" }));
        cbNormalizacao.setSelectedIndex(1);

        cbJanelamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLACKMAN", "HAMMING", "HANNING" }));

        jLabel7.setText("Janelamento:");

        jLabel14.setText("Ganho:");

        cbGanho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LINEAR", "LOGARITMICO" }));
        cbGanho.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbJanelamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbNormalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbGanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel14)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbJanelamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbNormalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbGanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbGanho;
    private javax.swing.JComboBox cbJanelamento;
    private javax.swing.JComboBox cbNormalizacao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txDesvioPadraoParaRuidosBrancos;
    private javax.swing.JTextField txFatorDistorcaoFrequencia;
    private javax.swing.JTextField txLimiteInferiorExtracaoF0;
    private javax.swing.JTextField txLimiteSuperiorExtracaoF0;
    private javax.swing.JTextField txOrdemAnaliseMGC;
    private javax.swing.JTextField txPesoPoleZeroAnaliseMGC;
    private javax.swing.JTextField txTamanhoFFT;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JComboBox getCbGanho() {
        return cbGanho;
    }

    public void setCbGanho(javax.swing.JComboBox cbGanho) {
        this.cbGanho = cbGanho;
    }

    public javax.swing.JComboBox getCbJanelamento() {
        return cbJanelamento;
    }

    public void setCbJanelamento(javax.swing.JComboBox cbJanelamento) {
        this.cbJanelamento = cbJanelamento;
    }

    public javax.swing.JComboBox getCbNormalizacao() {
        return cbNormalizacao;
    }

    public void setCbNormalizacao(javax.swing.JComboBox cbNormalizacao) {
        this.cbNormalizacao = cbNormalizacao;
    }

    public javax.swing.JTextField getTxDesvioPadraoParaRuidosBrancos() {
        return txDesvioPadraoParaRuidosBrancos;
    }

    public void setTxDesvioPadraoParaRuidosBrancos(javax.swing.JTextField txDesvioPadraoParaRuidosBrancos) {
        this.txDesvioPadraoParaRuidosBrancos = txDesvioPadraoParaRuidosBrancos;
    }

    public javax.swing.JTextField getTxFatorDistorcaoFrequencia() {
        return txFatorDistorcaoFrequencia;
    }

    public void setTxFatorDistorcaoFrequencia(javax.swing.JTextField txFatorDistorcaoFrequencia) {
        this.txFatorDistorcaoFrequencia = txFatorDistorcaoFrequencia;
    }

    public javax.swing.JTextField getTxLimiteInferiorExtracaoF0() {
        return txLimiteInferiorExtracaoF0;
    }

    public void setTxLimiteInferiorExtracaoF0(javax.swing.JTextField txLimiteInferiorExtracaoF0) {
        this.txLimiteInferiorExtracaoF0 = txLimiteInferiorExtracaoF0;
    }

    public javax.swing.JTextField getTxLimiteSuperiorExtracaoF0() {
        return txLimiteSuperiorExtracaoF0;
    }

    public void setTxLimiteSuperiorExtracaoF0(javax.swing.JTextField txLimiteSuperiorExtracaoF0) {
        this.txLimiteSuperiorExtracaoF0 = txLimiteSuperiorExtracaoF0;
    }

    public javax.swing.JTextField getTxOrdemAnaliseMGC() {
        return txOrdemAnaliseMGC;
    }

    public void setTxOrdemAnaliseMGC(javax.swing.JTextField txOrdemAnaliseMGC) {
        this.txOrdemAnaliseMGC = txOrdemAnaliseMGC;
    }

    public javax.swing.JTextField getTxPesoPoleZeroAnaliseMGC() {
        return txPesoPoleZeroAnaliseMGC;
    }

    public void setTxPesoPoleZeroAnaliseMGC(javax.swing.JTextField txPesoPoleZeroAnaliseMGC) {
        this.txPesoPoleZeroAnaliseMGC = txPesoPoleZeroAnaliseMGC;
    }

    public javax.swing.JTextField getTxTamanhoFFT() {
        return txTamanhoFFT;
    }

    public void setTxTamanhoFFT(javax.swing.JTextField txTamanhoFFT1) {
        this.txTamanhoFFT = txTamanhoFFT;
    }


}
