/**
 * Copyright 2011 Federal University of Pernambuco.
 * All Rights Reserved.  Use is subject to license terms.
 *
 * This file is part of FIVE (Framework for an Integrated Voice Environment).
 *
 */
package br.ufpe.cin.five.gui.speaker;

import br.ufpe.cin.five.core.speaker.Speaker;
import br.ufpe.cin.five.core.speaker.Gender;
import br.ufpe.cin.five.facade.Facade;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 *
 * @author Alexandre
 */
public class SpeakerDialog extends javax.swing.JDialog {

    private static final Logger logger = Logger.getLogger(SpeakerDialog.class);
    private Facade facade = Facade.getInstance();
    private int operation;   
    private Speaker speaker; 

    /** Creates new form SpeakerDialog */
    public SpeakerDialog(java.awt.Frame parent, boolean modal, Speaker speaker, int operation) {
        super(parent, modal);

        logger.info("Inicializando Speaker Dialog. Operation = " + operation);
        initComponents();
        
        this.operation = operation;
        this.speaker = speaker;
        
        cbGender.setModel(new DefaultComboBoxModel(Gender.values()));
        
        if (operation == 1) {
            tfName.setText(speaker.getName());
            tfAge.setText(String.valueOf(speaker.getAge()));
            tfRegion.setText(speaker.getRegion());
            cbGender.setSelectedItem(speaker.getGender());
        } else {
            this.speaker = new Speaker();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancel = new javax.swing.JButton();
        jlName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jlLogin = new javax.swing.JLabel();
        tfRegion = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        jlAge = new javax.swing.JLabel();
        tfAge = new javax.swing.JTextField();
        jlGender = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Locutor");

        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jlName.setText("Nome:");

        jlLogin.setText("Região:");

        btSave.setText("Salvar");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        jlAge.setText("Idade:");

        jlGender.setText("Gênero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlName)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlLogin)
                                        .addComponent(tfRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlAge)))
                                .addComponent(tfName))
                            .addComponent(jlGender)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addComponent(btSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancel)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogin)
                    .addComponent(jlAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSave)
                    .addComponent(btCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        logger.info("Botão btCancel pressionado.");
        this.setVisible(false);
}//GEN-LAST:event_btCancelActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        logger.info("Botão btSave pressionado. Operation = " + operation);
        if (validateFields()) {
            logger.info("Campos validados.");
            try {           
                speaker.setName(tfName.getText());
                speaker.setAge(Integer.parseInt(tfAge.getText()));
                speaker.setRegion(tfRegion.getText());
                speaker.setGender((Gender) cbGender.getSelectedItem());                                                                                   

                if(operation == 0) {
                    facade.insertSpeaker(speaker);
                    logger.info("Locutor inserido com sucesso!");
                    JOptionPane.showMessageDialog(null, "Locutor inserido com sucesso!");
                } else {
                    facade.updateSpeaker(speaker);            
                    logger.info("Locutor atualizado com sucesso!");
                    JOptionPane.showMessageDialog(null, "Locutor atualizado com sucesso!");            
                }        
                this.setVisible(false);        
            } catch (Exception ex) {
                logger.error(ex.getMessage());
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }                     
        } else {
            logger.warn("Informe os parâmetros necessários");
            JOptionPane.showMessageDialog(null, "Informe os parâmetros necessários");
        }       
}//GEN-LAST:event_btSaveActionPerformed

    private boolean validateFields() {
        if (tfName.getText().equals("")
                || tfRegion.getText().equals("")
                || tfAge.getText().equals("")
                || cbGender.getSelectedItem() == null) {                
            return false;
        } else {
            return true;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btSave;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JLabel jlAge;
    private javax.swing.JLabel jlGender;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlName;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfRegion;
    // End of variables declaration//GEN-END:variables
}
